### ISSUE TITLE
Passwords shouldn't be visible in plain text

### ISSUE THREAD

**Issue by JF10R** [MuffunKevin/OneClickToProd#7]
This is a security issue, especially when the SVN repository takes minutes to update.

**Comment by MuffunKevin** [comment]
This should do the work. Working on it.
https://msdn.microsoft.com/en-us/library/system.security.securestring.aspx

**Comment by MuffunKevin** [comment]
Supposed working exemple http://stackoverflow.com/a/3404464/428010
